osx_image: xcode9.2
language: swift
env:
  - TEST_SUITE=UnitTests COVERAGE='bundle exec fastlane coverage'
  - TEST_SUITE=IntegrationTests
cache:
  - bundler
  - cocoapods
branches:
  only:
  - master
before_install:
  - gem update --system
  - gem install bundler 
  - bundle install
  - pod repo update
  - pod install
script:
  - bundle exec fastlane test scheme:$TEST_SUITE
after_success:
  - $COVERAGE
