name: CI
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]
jobs:
  test:
    runs-on:  macos-14

    strategy:
      fail-fast: false
      matrix: 
        tests: ['UnitTests', 'IntegrationTests']

    steps:
    - name: Clone Repo
      uses: actions/checkout@v4
    
    - name: Gem Cache
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: CocoaPods Cache
      uses: actions/cache@v4
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Pod Install
      run: |
        bundle exec pod install

    - name: ${{ matrix.tests }} Tests
      run: |
        bundle exec fastlane test scheme:${{ matrix.tests }} os:17.2 name:"iPhone 15 Pro"
